# This is a basic workflow to help you get started with Actions

name: test me

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-me:
    runs-on: ubuntu-latest
    steps:
    - name: testing run 
      run: |
        echo "DEPLOYMENT_ENVIRONMENT=$([[ $GITHUB_REF = 'refs/heads/main' || $GITHUB_REF = 'refs/heads/master' ]] && echo "production" || echo "development")" >> $GITHUB_ENV
        echo "REPO=$(echo ${GITHUB_REPOSITORY#*/} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
        echo "DEPLOYMENT_CLUSTER=$([[ $DEPLOYMENT_ENVIRONMENT = "production" ]] && echo "figure-prod" || echo "figure-dev")" >> $GITHUB_ENV
        [[ -f ${GITHUB_ENV} ]] && cat $GITHUB_ENV
  
